apiVersion: v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: my-namespace
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:       
      - pathType: Prefix
        path: /foo
        backend:
          service:
            name: hello-world-sample
            port:
              number: 4200